---

- src: https://github.com/OULibraries/ansible-role-centos7
  scm: git
  version: master
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-postgresql-server
  scm: git
  version: master
  name: OULibraries.postgresql-server

- src: https://github.com/OULibraries/ansible-role-dspace
  scm: git
  version: master
  name: OULibraries.dspace

- src: https://github.com/OULibraries/ansible-role-lastpass-cli
  scm: git
  version: master
  name: OULibraries.lastpass-cli
  
- src: https://github.com/OULibraries/ansible-role-lastpass-dspace
  scm: git
  version: master
  name: OULibraries.lastpass-dspace

