---
# fetch jsnshrmn.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: jsnshrmn.centos7
# fetch lo5an.dspace from github
- src: https://github.com/OULibraries/ansible-role-postgresql-server
  version: master
  scm: git
  name: oulibraries.postgresql-server
# fetch jsnshrmn.ngrok from github
- src: https://github.com/OULibraries/ansible-role-ngrok
  version: master
  name: jsnshrmn.ngrok
