---
# fetch jsnshrmn.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: jsnshrmn.centos7
# fetch jsnshrmn.d7 from github
- src: https://github.com/OULibraries/ansible-role-dspace
  version: master
  name: lo5an.dspace
# fetch jsnshrmn.ngrok from github
- src: https://github.com/OULibraries/ansible-role-ngrok
  version: master
  name: jsnshrmn.ngrok
