---
- hosts: localhost
  roles:
    - OULibraries.lastpass-dspace

- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.centos7
    - OULibraries.postgresql-server
    - OULibraries.dspace
  tasks:
    - name: Disable selinux for vagrant
      selinux: state=disabled
